Astro example
vercel/turbo pull request #1780
Opened 2022-08-26 10:32 UTC by neolivz

Similar to basic but with two component libraries, one with react and the other with svelte (taken from with-svelte). Both are imported into web, docs Astro projects

2022-08-26 10:39 UTC, neolivz commented
Is there any particular version of pnpm i need to use to generate the lockfile?

2022-08-30 19:54 UTC, mehulkar reviewed
Couple q's:

- For @vercel/turbo-oss: are we indefinitely adding examples for frameworks as we get contributions? 
- For @neolivz: Is it expected that the root `pnpm-lock.yaml` changed? I'm not familiar with pnpm, so I'm not sure if it's due to the new example, or if there is an additional update here that is unrelated.

2022-09-01 11:44 UTC, nathanhammond requested changes
Here's a first pass, hoping that you can sort through these!

2022-09-01 11:44 UTC, nathanhammond commented on .gitignore
> +pnpm-debug.log*
Let's put these changes in a separate PR.

2022-09-01 11:44 UTC, nathanhammond commented on .gitignore
> +.env.production
```suggestion
.env*
```

2022-09-01 11:44 UTC, nathanhammond commented on .gitignore
> +.output/
I'm not sure what this is for? What is populating this directory?

2022-09-01 11:44 UTC, nathanhammond commented on pnpm-lock.yaml
> +      tailwindcss: 3.1.8_postcss@8.4.16
Let's remove the lockfile changes from this PR.

2022-09-01 11:44 UTC, nathanhammond commented on examples/with-astro/package.json
> +  "packageManager": "pnpm@6.25.1"
We don't specify package manager for any of our examples except for scenarios where it is explicitly required. This is not one of those cases.

2022-09-01 11:44 UTC, nathanhammond commented on examples/with-astro/package.json
> +    "npm": ">=7.0.0",
```suggestion
```

2022-09-01 11:44 UTC, nathanhammond commented on examples/with-astro/package.json
> +    "prettier": "latest",
Let's actually specify a version here.

2022-09-01 11:44 UTC, nathanhammond commented on examples/with-astro/package.json
> +    "eslint-config-custom": "workspace:*",
```suggestion
    "eslint-config-custom": "*",
```

2022-09-01 11:44 UTC, nathanhammond commented on examples/with-astro/packages/tsconfig/package.json
> +}
We just changed our strategy for this, would you mind updating this file?

2022-09-01 11:44 UTC, nathanhammond commented on examples/with-astro/README.md
> +# Turborepo starter with pnpm
Many parts of this are not updated, can you correct this? (docs & web are astro, for example)

2022-09-01 11:44 UTC, nathanhammond commented on examples/with-astro/apps/docs/astro.config.mjs
> +import svelte from "@astrojs/svelte";
Is it expected to use both React and Svelte in an Astro setup?

2022-09-01 11:44 UTC, nathanhammond commented on examples/with-astro/apps/docs/README.md
> +| `npm install`          | Installs dependencies                            |
Since the generator for astro spits out `npm`, we shouldn't use `pnpm`.

2023-04-17 13:36 UTC, tknickman commented
Hey @neolivz, apologies for letting this sit for a bit - I'd be happy to take another pass at this and get it in if you have the time to update it!

2023-05-01 13:46 UTC, closed without merging

2024-08-09 17:21 UTC, kmalloy24 commented
@tknickman I have a working version of this that I can send as a fresh PR if you are interested. 

https://github.com/kmalloy24/with-turbo/tree/main/sveltekit-astro