Update Cargo dependencies, add shim into Cargo workspace
vercel/turbo pull request #2359
Opened 2022-10-26 06:29 UTC by Brooooooklyn

2022-10-26 15:28 UTC, NicholasLYang requested changes

2022-10-26 15:28 UTC, NicholasLYang commented on Cargo.toml
> +  "shim",
There's an exclude rule for the shim that we'll need to remove too

2022-10-26 15:28 UTC, NicholasLYang commented on crates/next-core/src/nodejs/mod.rs
> +            return static_error(path, err, None, fallback_page).await;
Any reason for these changes? Clippy?

2022-10-26 16:17 UTC, Brooooooklyn commented on crates/next-core/src/nodejs/mod.rs
> +            return static_error(path, err, None, fallback_page).await;
yes, clippy fixed it

2022-10-26 17:01 UTC, jridgewell approved these changes

2022-10-26 17:01 UTC, jridgewell commented on shim/build.rs
> +    let cli_path = env::current_dir().unwrap().parent().unwrap().join("cli");
Should this be using [CARGO_WORKSPACE_DIR](https://github.com/vercel/turbo/blob/1628df924e8e4d57046dbb00f325769cf808ec6d/.cargo/config.toml#L2) instead?

2022-10-27 03:25 UTC, Brooooooklyn commented on crates/turbopack-cli-utils/src/issue.rs
> +    fn to_possible_value<'a>(&self) -> Option<clap::builder::PossibleValue> {
it because the `clap` was upgraded

2022-10-27 18:12 UTC, jridgewell approved these changes

2022-10-28 11:16 UTC, Brooooooklyn commented
not sure why `turbo` tests failed on CI, @NicholasLYang can you take a look?

2022-10-28 16:02 UTC, NicholasLYang commented
Ah, clap changed its help output in v4, so bumping it broke some tests. Also adding shim to the cargo workspace broke a couple things. Fixing it....

2022-11-10 03:33 UTC, closed without merging