Mention missing css @import(uri) support in docs
vercel/turbo pull request #2571
Opened 2022-11-02 23:14 UTC by wbinnssmith

This adds a note to the css section of the Turbopack docs that `@import` of absolute uris is not yet supported and suggests using a link tag as an alternative.

2022-11-02 23:43 UTC, padmaia commented on docs/pages/pack/docs/features/css.mdx
> +</Callout>
This is Next.js specific advice, right? Maybe "To work around this in Next.js, " instead? Also did I hear this advice only works in pages?

2022-11-03 08:35 UTC, sokra approved these changes

2022-11-03 11:36 UTC, alexkirsz requested changes

2022-11-03 11:36 UTC, alexkirsz commented on docs/pages/pack/docs/features/css.mdx
> +  Turbopack does not currently support absolute uri imports in css, such as `@import(https://example.com/stylesheet.css)`. As a workaround, add
```suggestion
  Turbopack does not currently support absolute URI imports in css, such as `@import(https://example.com/stylesheet.css)`. As a workaround, add
```

2022-11-03 11:36 UTC, alexkirsz commented on docs/pages/pack/docs/features/css.mdx
> +  Turbopack does not currently support absolute uri imports in css, such as `@import(https://example.com/stylesheet.css)`. As a workaround, add
Isn't the syntax `@import url("https://example.com/stylesheet.css");`?

2022-11-03 11:36 UTC, alexkirsz commented on docs/pages/pack/docs/features/css.mdx
> +  [add this to `pages/_document.js`](https://nextjs.org/docs/messages/no-page-custom-font#possible-ways-to-fix-it).
Next.js 13 also has `app/layout.js`: https://beta.nextjs.org/docs/routing/pages-and-layouts#root-layout-required

I'm not sure whether we support this yet.

2022-11-03 15:58 UTC, alexkirsz approved these changes

2022-11-03 15:58 UTC, alexkirsz commented on docs/pages/pack/docs/features/css.mdx
> +  `<link rel="stylesheet" href="https://example.com/stylesheet.css"></link>` to your HTML document. Next.js users using `pages/` should
```suggestion
  `<link rel="stylesheet" href="https://example.com/stylesheet.css" />` to your HTML document. Next.js users using `pages/` should
```

2022-11-04 14:37 UTC, jaredpalmer requested changes
Need to update for next 13 layout

2022-11-04 14:38 UTC, merged