Add query structure to module requests
vercel/turbo pull request #2743
Opened 2022-11-17 00:02 UTC by wbinnssmith

This adds a query field to the module struct in the request enum. Currently, specifiers that include a queryparam-like `?foo=bar` are treated as literal parts of the filename. This change means that (at least for module requests for the time being), this query param is no part of the file name during resolving.

Test Plan: The @next/font snapshot test no longer emits issues re: a missing file.

2022-11-17 00:02 UTC, wbinnssmith commented
Current dependencies on/for this PR:
* main
  * **PR #2742** <a href="https://app.graphite.dev/github/pr/vercel/turbo/2742" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #2743** <a href="https://app.graphite.dev/github/pr/vercel/turbo/2743" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/vercel/turbo/2743?utm_source=stack-comment).

2022-12-01 20:52 UTC, ForsakenHarmony approved these changes

2022-12-02 18:57 UTC, jridgewell requested changes

2022-12-02 18:57 UTC, jridgewell commented on crates/turbopack-core/src/resolve/pattern.rs
> +    }
Why create an empty query that can't be further modified? Shouldn't this be the same as the `none` case, to avoid allocating the `IndexMap`?

2022-12-02 18:57 UTC, jridgewell commented on crates/turbopack-core/src/resolve/parse.rs
> +                                query: QueryMapVc::cell(query.map(|q| {
Nit: Can this be done later? Eg, instead of splitting the `path` and `query` now, could this be done only when the import actually happens?

2022-12-02 18:57 UTC, jridgewell commented on crates/next-dev/src/lib.rs
> +                QueryMapVc::cell(None),
```suggestion
                QueryMapVc::none(),
```

2022-12-05 20:21 UTC, jridgewell approved these changes
My personal desire is for the query string to stop being used, and instead use import assertions to give add metadata. The current approach matches roughly with how we would approach that, so LGTM.

2022-12-05 20:24 UTC, wbinnssmith commented
> My personal desire is for the query string to stop being used, and instead use import assertions to give add metadata. The current approach matches roughly with how we would approach that, so LGTM.

Totally agree. Would be nice to use import assertions in places webpack and others use things like magic comments (for preload hints, chunk naming, etc.) [0] and inline loaders [1] as well

[0] https://webpack.js.org/api/module-methods/#magic-comments
[1] https://webpack.js.org/concepts/loaders/#inline

2022-12-05 21:47 UTC, merged