chore: move turborepo tests to primary workflow
vercel/turbo pull request #2771
Opened 2022-11-19 01:14 UTC by chris-olszewski

2022-11-21 05:19 UTC, sokra requested changes

2022-11-21 05:19 UTC, sokra commented on .github/workflows/test.yml
> +        id: tests
Maybe make it a little bit more specific, like `cli_tests` or `go_tests` or `repo_tests`

2022-11-21 05:19 UTC, sokra commented on .github/workflows/test.yml
> +            cli/integration_tests/**/*.t
```suggestion
            cli/integration_tests/**
```

There are some `*.sh` files or `turbo.json`s in these tests that should probably also trigger a test run

2022-11-21 05:19 UTC, sokra commented on .github/workflows/test.yml
> +      runs-on: ${{ matrix.os }}
There is a `runs-on: ${{ matrix.os.runner }}` a few lines below.

Also there is no `runs-on` in `strategy`

2022-11-21 05:19 UTC, sokra commented on .github/actions/build-debug-turborepo/action.yml
> +    - uses: actions-rs/toolchain@v1
Give these steps names

2022-11-21 05:19 UTC, sokra commented on .github/workflows/test.yml
> +        os: [ubuntu-latest, macos-latest]
```suggestion
    if: needs.determine_jobs.outputs.go == 'true' || needs.determine_jobs.outputs.tests == 'true'
    strategy:
      matrix:
        os:
          - name: ubuntu
            runner: ubuntu-latest
          - name: macos
            runner: macos-latest
    runs-on: ${{ matrix.os.runner }}
    name: Cram integration tests on ${{ matrix.os.name }}
```

You could switch to `runner: ubuntu-latest-16-core-oss` if you want this to be faster, but it costs ~$3/h

2022-11-21 05:19 UTC, sokra commented on .github/workflows/test.yml
> +        os: [ubuntu-latest, macos-latest, windows-latest]
```suggestion
    needs: [determine_jobs, rust_prepare]
    if: needs.determine_jobs.outputs.go == 'true' || needs.determine_jobs.outputs.tests == 'true'
    strategy:
      matrix:
        os:
          - name: ubuntu
            runner: ubuntu-latest
          - name: macos
            runner: macos-latest
          - name: windows
            runner: windows-latest
    runs-on: ${{ matrix.os.runner }}
    name: Build Turborepo for ${{ matrix.os.name }}
```

Seems like `runs-on` is missing here?

You could switch to `runner: ubuntu-latest-16-core-oss` if you want this to be faster, but it costs ~$3/h

2022-11-21 05:19 UTC, sokra commented on .github/workflows/test.yml
> +      runs-on: ${{ matrix.os }}
```suggestion
```

2022-11-21 05:19 UTC, sokra commented on .github/workflows/test.yml
> +    if: needs.determine_jobs.outputs.go == 'true' || needs.determine_jobs.outputs.tests == 'true' || needs.determine_jobs.outputs.node == 'true'
Why does this need to run when `node` has changed? If this depends on some JS files you can add these files to the `go` diff and remove that

2022-11-21 05:19 UTC, sokra commented
Also make sure to remove the old workflow files in this PR too

2022-11-29 04:19 UTC, chris-olszewski commented
Closing in favor of #2854

2022-11-29 04:19 UTC, closed without merging