read env vars from next.config.js
vercel/turbo pull request #3128
Opened 2022-12-22 17:01 UTC by ForsakenHarmony

2022-12-22 17:01 UTC, ForsakenHarmony commented
Current dependencies on/for this PR:
* main
  * **PR #3105** <a href="https://app.graphite.dev/github/pr/vercel/turbo/3105" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #3128** <a href="https://app.graphite.dev/github/pr/vercel/turbo/3128" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/vercel/turbo/3128?utm_source=stack-comment).

2022-12-23 15:43 UTC, alexkirsz approved these changes

2023-01-12 06:47 UTC, jridgewell requested changes

2023-01-12 06:47 UTC, jridgewell commented on crates/next-core/src/env.rs
> +    }
This is happening post encoding (via the `EmbeddableProcessEnvVc`), which means a `{ env: "alert('XSS')" }` injects live code and will actually alert the user.

2023-01-17 17:42 UTC, jridgewell approved these changes

2023-01-17 17:51 UTC, merged