Handle 404 page when getStaticProps.notFound = true
vercel/turbo pull request #3448
Opened 2023-01-24 10:42 UTC by alexkirsz

This specifically supports the case where `getStaticProps.notFound = true`, but not the following cases:

- `getStaticPaths.fallback = false` and the route is not enumerated;
- no matching route is found.

These two cases will be implemented in separate PRs.

2023-01-24 10:43 UTC, alexkirsz commented
Current dependencies on/for this PR:
* main
  * **PR #3435** <a href="https://app.graphite.dev/github/pr/vercel/turbo/3435" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #3448** <a href="https://app.graphite.dev/github/pr/vercel/turbo/3448" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/vercel/turbo/3448?utm_source=stack-comment).

2023-01-24 12:10 UTC, sokra requested changes
Isn't it better to respond with `Rewrite("/404")` instead of compiling the error and 404 page into every page?

2023-01-26 15:00 UTC, sokra approved these changes

2023-01-26 15:20 UTC, alexkirsz commented on crates/next-core/js/src/internal/page-server-handler.tsx
> +    // Both _error and 404 should receive a 404 status code.
When navigating to `/_error` in Next.js, a 404 status is always returned.

2023-01-27 03:44 UTC, jridgewell commented on crates/turbopack-ecmascript/src/references/esm/module_id.rs
> +                    }));
Nit:
```suggestion
                    *expr = quote!("null" as Expr);
```

2023-01-27 03:44 UTC, jridgewell commented on crates/turbopack-ecmascript/src/references/esm/module_id.rs
> +};
Nit:
```suggestion
use swc_core::{ecma::ast::Expr, quote};
```

2023-01-27 03:44 UTC, jridgewell commented on crates/turbo-tasks-fs/src/lib.rs
> +    pub fn with_status_code(mut self, status_code: u16) -> Self {
I think this is the wrong level for this API, and I'm glad the follow up PR is removing it.

2023-01-27 03:44 UTC, jridgewell commented on crates/next-core/src/page_source.rs
> +    for ext in ["js", "ts", "jsx", "tsx", "mdx"] {
I think this needs to updated to hook into the next-config's extensions?

2023-01-27 03:44 UTC, jridgewell commented on crates/next-core/src/next_route_matcher/prefix_suffix.rs
> +    fn strip_prefix_and_suffix<'a, 'b>(&'a self, path: &'b str) -> Result<Option<&'b str>> {
Nit: Can we unnest this?

```suggestion
    fn strip_prefix_and_suffix<'a, 'b>(&'a self, path: &'b str) -> Option<&'b str> {

2023-01-27 09:20 UTC, alexkirsz commented on crates/turbopack-node/src/route_matcher.rs
> +pub trait RouteMatcher {
It belongs at the same level as `NodeRenderContentSource`, which is the only thing that actually calls into it, and that's in `turbopack-node` at the moment.

2023-01-27 13:38 UTC, merged

2023-03-29 01:39 UTC, ForsakenHarmony commented on crates/next-core/js/src/entry/error.tsx
> +export { getStaticProps };
this is actually not supported by next.js

https://nextjs.org/docs/advanced-features/custom-error-page#caveats