[FIX]: VSCode Parsing error: Cannot find module 'next/babel PNPM Eslint
vercel/turbo pull request #3489
Opened 2023-01-26 06:29 UTC by ImBIOS

# 🪲 Error Reported

```bash
Parsing error: Cannot find module 'next/babel'
```

# 💻 Where does the Error Spawn?

Requirements:

1. PNPM
2. ESLint
3. Monorepo (Turporepo)

If all of the above requirements ✅ checked, you can see the Error in every ESLint config file in the children directories.

# 🤔 Cause

Still needed to figure out why does this happen. My hypothesis as it is because of the PNPM node_modules design that is read by VSCode's ESLint extension.

2023-01-26 06:33 UTC, ImBIOS commented
Please don't merge it, I still want to add this fix to every affected examples as much as I could.

2023-01-26 06:57 UTC, ImBIOS commented
Good 👍 to go now, I already edit all potentially affected examples and edited the error I found in `examples/basic` 🚀

2023-01-26 14:11 UTC, tknickman requested changes
Thanks for the PR! left a few comments, but would love to get this one in.

2023-01-26 14:11 UTC, tknickman commented on examples/kitchen-sink/packages/eslint-config-custom-server/index.js
> +      presets: [require.resolve('next/babel')],
We shouldn't need this here, this config is for server apps only and doesn't extend from next

2023-01-26 14:11 UTC, tknickman commented on examples/with-create-react-app/packages/eslint-config-custom/index.js
> +      presets: [require.resolve('next/babel')],
We shouldn't need this one either, this example is for CRA and not Next (doesn't extend from next)

2023-01-26 14:11 UTC, tknickman commented on examples/with-docker/packages/eslint-config-custom-server/index.js
> +      presets: [require.resolve('next/babel')],
One more, this config shouldn't be required here since we're not extending from next for this config.

2023-01-26 14:11 UTC, tknickman commented on examples/with-svelte/packages/eslint-config-custom/index.js
> +      presets: [require.resolve('next/babel')],
Can remove, this example is for svelte, not next.

2023-01-26 14:11 UTC, tknickman commented on examples/with-vite/packages/eslint-config-custom/index.js
> +      presets: [require.resolve('next/babel')],
Can remove, this example is for vite, not next.

2023-01-27 03:12 UTC, tknickman approved these changes

2023-01-27 03:13 UTC, tknickman commented
Awesome, thanks!

2023-01-27 03:13 UTC, merged

2023-04-29 07:08 UTC, tunguyen-ct commented
@tknickman @ImBIOS This fix can silent the error of VSCode ESLint extension, however the VSCode ESLint extension also stop working.

You can see the Output of ESLint extention:

<img width="1032" alt="Screenshot 2023-04-29 at 14 07 45" src="https://user-images.githubusercontent.com/93700515/235289021-543c0f4e-78cd-4e27-b24d-a0ce6cefff4a.png">

```
Error: Cannot find module 'next/babel'
```

2023-04-29 08:45 UTC, ImBIOS commented
I think we should find the root cause and solve it.