use apply when expanding amd pattern matches
vercel/turbo pull request #3677
Opened 2023-02-07 18:12 UTC by ForsakenHarmony

2023-02-07 20:10 UTC, sokra requested changes

2023-02-08 20:24 UTC, ForsakenHarmony commented
Current dependencies on/for this PR:
* main
  * **PR #3677** <a href="https://app.graphite.dev/github/pr/vercel/turbo/3677" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/vercel/turbo/3677?utm_source=stack-comment).

2023-02-08 20:26 UTC, ForsakenHarmony commented on crates/turbopack-ecmascript/src/references/amd.rs
> +                                .context("amd request pattern can't be turned into a string")?,
fixed, also refactored things a bit

2023-02-09 09:12 UTC, alexkirsz approved these changes

2023-02-09 18:21 UTC, merged