Implement Rewrite Headers support during routing
vercel/turbo pull request #3897
Opened 2023-02-21 22:01 UTC by jridgewell

The final piece to supporting Rewrites is implementing support for overwriting **response** headers. These overwritten headers need to be collected until we resolve into a final `ContentSourceContent::Static` (which gets turned into `ResolveSourceRequestResult`, then `GetFromSourceResult`) to be returned into the HTTP response.

I chose to implement this as an external list from the headers already present in a `ContentSourceContent::Static`. It felt wrong to `content.await?` just to overwrite the returned headers, and then repackage that as a new `ContentSourceContentVc`. These `header_overwrites` exist only as a byproduct of route resolution, and specifically the exact path of rewrites we go through to get there. They're not intrinsic to the `ContentSourceContent` itself.

Fixes WEB-617

2023-02-21 22:14 UTC, sokra requested changes
Test case

2023-02-21 22:15 UTC, wbinnssmith approved these changes

2023-02-21 22:15 UTC, jridgewell commented
I'm working on the test cases for Rewrite/Redirect/Headers now.

2023-02-21 22:54 UTC, jridgewell commented
Tests implemented for Rewrite/Redirect, but the Headers support [**just landed**](https://github.com/vercel/next.js/commit/185a8921c878fb6fff46d9fc299683ee689d3415#diff-b8d76362f52dfa3141163a91f6dc67dbfe72242de22db1c388c387698031eb6eR142) in Next side and I can't test it until we update our canary dep.

2023-02-21 23:07 UTC, jridgewell commented
I've manually confirmed this works once by duplicating https://github.com/vercel/next.js/commit/185a8921c878fb6fff46d9fc299683ee689d3415.

2023-02-21 23:08 UTC, padmaia approved these changes

2023-02-22 00:40 UTC, merged

2023-02-22 00:41 UTC, jridgewell commented
Merging over some test flake.

2023-02-22 07:09 UTC, sokra commented
> Merging over some test flake.

kodiak could handle this now. It won't block on mac or windows CI anymore.