Remove sharp dev dep
vercel/turbo pull request #3994
Opened 2023-02-27 23:07 UTC by jridgewell

This native addon build is failing: https://github.com/vercel/turbo/actions/runs/4287144906/jobs/7467736436

2023-02-27 23:14 UTC, wbinnssmith approved these changes

2023-02-28 08:23 UTC, sokra approved these changes

2023-02-28 08:24 UTC, sokra requested changes
It seem to be working again...

2023-03-01 02:35 UTC, jridgewell commented
Yup, looks like whatever outage caused it resolved itself.

2023-03-01 02:35 UTC, closed without merging