fix next.js source map resolving
vercel/turbo pull request #4062
Opened 2023-03-03 12:13 UTC by sokra

### Description

Before the error overlay didn't show the source mapped file.
Now it does.

* The wrapped ContentSources need to wrap a Rewrite result.
* Instead of returning a ContentSourceResult from a different ContentSource, one need to use Rewrite to get the data correct.

### Testing Instructions

Throw an error in an next.js app that triggers the error overlay with stack trace.

2023-03-04 07:05 UTC, jridgewell requested changes

2023-03-04 07:05 UTC, jridgewell commented on crates/turbopack-node/src/source_map/content_source.rs
> +            ContentSourceContent::Rewrite(
I don't understand why these need to be rewrites. We're not expecting query params, right? We're not changing headers. This should be equivalent to just doing the `.get()` directly, right?

2023-03-09 10:41 UTC, sokra commented on crates/turbopack-dev-server/src/source/wrapping_source.rs
> +                    ),
We won't hit ourselves since we changed the `path`. So we need to make sure to always provide a source.

2023-03-09 18:52 UTC, jridgewell approved these changes

2023-03-09 18:52 UTC, jridgewell commented on crates/turbopack-node/Cargo.toml
> +urlencoding = { workspace = true }
```suggestion
```

2023-03-09 18:52 UTC, jridgewell commented on crates/turbopack-dev-server/src/source/source_maps.rs
> +fn encode_pathname_to_url(pathname: &str) -> String {
Can you add a comment on why we need to encode the pieces between `/`s?

2023-03-09 19:00 UTC, merged