Add clinia as a company that uses Turbo
vercel/turbo pull request #4073
Opened 2023-03-04 14:13 UTC by etiennecl

Very grateful to be able to have proper tooling and all the work that you guys are putting into Turbo. As we are migrating all of our frontend to Turborepo and all of our upcoming open-source frontend libraries, we would be honored to have our logo on the showcase page.

2023-03-06 20:28 UTC, NicholasLYang approved these changes

2023-03-07 22:15 UTC, mehulkar commented
@etiennecl the prettier check is failing:

```
//:check:prettier: [warn] docs/components/clients/users.ts
```
could you run `prettier -w docs/components/clients/users.ts` and commit / push again?

2023-03-21 16:27 UTC, mehulkar requested changes

2023-03-21 16:27 UTC, mehulkar commented on docs/components/clients/users.ts
> +    infoLink: "https://clinia.dev/",
This URL doesn't resolve for me, is it temporarily down or is there a typo?

2023-05-15 16:46 UTC, rakesh-gupta29 commented
I think the link should be https://clinia.com/en-ca

2023-06-09 16:45 UTC, mehulkar commented
@etiennecl closing this down due to inactivity, but let me know if you want to open it up again!

2023-06-09 16:45 UTC, closed without merging