Chunking Refactor pt. 2
vercel/turbo pull request #4450
Opened 2023-04-04 15:28 UTC by alexkirsz

### Description

Previous episode: https://github.com/vercel/turbo/pull/4397

In this episode, we:

1. Get rid of `ChunkGroupVc`. `ChunkGroupVc` previously took care of:
  a. optimizing chunks;
  b. adding additional chunks, such as the "evaluate" chunk, which evaluates runtime entries.
  Both of these use cases are a concern of the chunking context (i.e. it would differ between dev and build), hence they're now handled by the chunking context.
2. Move the chunk list registration logic into a different chunk. The chunk list was previously a bit leaky as it required the Next.js code to instantiate it manually. There were also a bunch of other instantiations in the code which differed ever so slightly. The chunk list registration code is now part of a separate chunk, which is only added by the dev chunking context.

### Testing Instructions

Snapshots + Next dev tests + Manual tests

2023-04-05 17:29 UTC, sokra requested changes
Let's wait until after the next.js release before merging that

2023-04-06 08:00 UTC, alexkirsz commented on crates/turbopack-core/src/chunk/mod.rs
> +        let set = self.chunks.await?.clone_value();
If I'm not mistaken, this specific line was always eager. However, creating a chunk group reference was not.

2023-04-06 08:16 UTC, alexkirsz commented on crates/turbopack-core/src/chunk/mod.rs
> +                .join(", ")
Since we now store the entry directly, I'm printing the entry's ident here.

2023-04-11 14:25 UTC, sokra approved these changes
Great to see all these `__turbopack_register_chunk_list__()` calls to be gone

2023-04-11 14:25 UTC, sokra commented on crates/turbopack-dev/src/chunking_context.rs
> +        .flatten())
The `Chunk` trait should have a `parallel_chunks()` method to expose parallel chunks. `references()` should no longer contain parallel chunks

2023-04-11 15:15 UTC, merged

2023-04-11 15:15 UTC, alexkirsz commented
The remaining comments will be addressed in pt. 3.

2023-04-12 08:56 UTC, alexkirsz commented on crates/turbopack-dev/src/chunking_context.rs
> +                chunk.into()
Yes, this will eventually have to go. But for now, in order to keep supporting CSS chunks without modifications, we have to do this.