Better dotenv error messages
vercel/turbo pull request #4464
Opened 2023-04-04 23:26 UTC by jridgewell

The issue message emitted by `TryDotenvProcessEnv` was pretty bad: `Execution of TryDotenvProcessEnv::read_all failed`. This error message comes from #3550, which attaches the calling function as the context for every failed turbo function.

This PR accomplishes 2 main things:
1. Expose an explicit method determining whether a the `DotenvEnvProcess`'s prior or current env failed
2. Detects a current env failure and uses the error's root cause for the issue message.

Fixes WEB-851

2023-04-05 22:05 UTC, sokra requested changes

2023-04-05 22:05 UTC, sokra commented on crates/turbo-tasks-env/src/dotenv.rs
> +    pub async fn try_read_all(&self) -> Result<DotenvReadResult> {
You could avoid all this complicate logic by making in a two step process:

```
#[turbo_tasks::function]
pub fn read_all_prior(self) -> Result<EnvMapVc> { ... }

#[turbo_tasks::function]
pub fn read_all_with_prior(self, prior: EnvMapVc) -> Result<EnvMapVc> { ... }
```

2023-04-05 22:05 UTC, sokra commented on crates/turbopack-env/src/try_env.rs
> +        }
With the two step process you can handle it like:

```
let prior = dotenv.read_all_prior();
let prior = match prior.resolve().await {
  Ok(p) => p,
  Err(err) => { /* handle prior error */ }
}
match dotenv.read_all_with_prior(prior).await {
  Ok(p) => { ... }
  Err(err) => { /* handle current error */ }
}
```

2023-04-05 23:21 UTC, jridgewell reviewed
Oh wow, I don't know why I didn't see the potential to split the methods. Done.

2023-04-06 10:29 UTC, sokra approved these changes

2023-04-06 10:29 UTC, merged