chore: Prefix all turborepo crates with turborepo-
vercel/turbo pull request #4853
Opened 2023-05-05 21:15 UTC by NicholasLYang

### Description

To make filtering for CI and other tasks easier, we're prefixing all turborepo crates with `turborepo-`. That way, filtering can be done as `crates/turborepo-*`.

### Testing Instructions

2023-05-05 21:52 UTC, mehulkar approved these changes

2023-05-05 21:53 UTC, mehulkar reviewed
Can you change the input patterns in the test.yml and other github workflows also?

2023-05-08 18:23 UTC, mehulkar approved these changes

2023-05-11 09:53 UTC, alexkirsz requested changes

2023-05-11 09:53 UTC, alexkirsz commented on .github/CODEOWNERS
> +/crates/turborepo-* @vercel/turbo-oss
```suggestion
/crates/turborepo* @vercel/turbo-oss
```
Otherwise it doesn't include turborepo itself.

2023-05-11 09:53 UTC, alexkirsz commented on .github/workflows/test.yml
> +            !crates/turborepo-*/**
```suggestion
            !crates/turborepo*/**
```

2023-05-11 09:53 UTC, alexkirsz commented on .github/workflows/test.yml
> +            crates/turborepo-*/**
```suggestion
            crates/turborepo*/**
```

2023-05-11 09:57 UTC, alexkirsz requested changes

2023-05-11 09:57 UTC, alexkirsz commented on Cargo.toml
> +  "crates/turborepo-updater",
This is covered by crates/turborepo* below.

2023-05-12 08:17 UTC, alexkirsz approved these changes

2023-05-16 17:46 UTC, closed without merging