Mark Vcs as `must-use`
vercel/turbo pull request #5387
Opened 2023-06-26 22:01 UTC by wbinnssmith

This uses the `#[must-use]` macro [0] to mark Vcs as needing to be used when created. The compiler creates warnings for each case.

Test Plan: Create a Vc in code and verify a warning is shown when Turbopack is built.

[0] https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-must_use-attribute

2023-06-26 22:44 UTC, ForsakenHarmony approved these changes

2023-06-26 22:49 UTC, jridgewell requested changes
I think we need this on TraitVcs and possibly on TT function return values?
- https://github.com/vercel/turbo/blob/wbinnssmith/3a6d5fce/crates/turbo-tasks-macros/src/value_trait_macro.rs#L247-L250
- https://github.com/vercel/turbo/blob/wbinnssmith/3a6d5fce/crates/turbo-tasks-macros/src/function_macro.rs#L42-L46

2023-06-27 07:47 UTC, sokra commented on crates/turbo-tasks-memory/tests/collectibles.rs
> +    my_transitive_emitting_function("", "a").await?;
Better use `let _ =` for these two

2023-06-27 07:49 UTC, sokra commented on crates/turbopack/src/lib.rs
> +            result.add_reference(types_reference.into()).await?;
This probably returns a new result. Maybe rename the function to `with_reference`

```suggestion
            result = result.add_reference(types_reference.into());
```

2023-06-29 19:35 UTC, jridgewell approved these changes

2023-06-29 19:35 UTC, jridgewell commented on crates/turbo-tasks-macros/src/func.rs
> +                "Cannot return `()` from a turbo_tasks function. Return Result<NothingVc> instead.",
```suggestion
                "Cannot return `()` from a turbo_tasks function. Return a NothingVc instead.",
```

2023-06-30 22:00 UTC, merged