Add support for `"workspaces"` config objects in yarn
vercel/turbo pull request #5439
Opened 2023-07-01 12:51 UTC by eykrehbein

### Description

To be able to use the [`nohoist` config](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/) in yarn workspaces, an object with the keys `nohoist` and `packages` needs to be provided for the `"workspaces"` entry in package.json. 

The proposed changes add support for a non-array `workspaces` entry in `package.json` when using yarn. Before that, only arrays were supported which let to the following exception inside the `expandWorkspaces` function when using an object:

```
>>> Unexpected error. Please report it as a bug:
r.flatMap is not a function
```

A function (`parseWorkspacePackages`) was introduced to dynamically parse the `"workspaces"` config by reusing the logic that was already introduced to parse `pnpm` configs.

### Testing Instructions

The given test for yarn was adapted to use a `workspaces` object instead of an array

2023-07-06 13:33 UTC, arlyon commented
Hm, odd behaviour from yarn to say the least but I am open to including this. @tknickman is the generator master but he is away right now so I will take over. Going to run CI first then have a look, thanks!

2023-07-11 08:39 UTC, eykrehbein commented
@arlyon Is there anything I can do from my side right now? 🙂

2023-07-13 07:05 UTC, arlyon commented
I am merging in main to this branch to see if it helps with CI. This 'symmetric difference' error pops up every once in a while.

2023-07-17 19:28 UTC, chris-olszewski requested changes
Thanks for adding support for this! Only two minor changes and I think this is ready to go. Sorry for the delay on the review.

2023-07-17 19:28 UTC, chris-olszewski commented on packages/turbo-workspaces/src/utils.ts
> +        return parseWorkspacePackages({ workspaceConfig });
`pnpm` doesn't need to share this codepath as `pnpm-workspace.yaml` has it's own schema.

2023-07-17 19:28 UTC, chris-olszewski commented on packages/turbo-workspaces/src/managers/npm.ts
> +        workspaceGlobs: packageJson.workspaces as Array<string> | undefined,
`npm` also supports declaring workspaces via `"workspaces": { "packages": ["package/a"] }` so we should use the `parseWorkspacePackages` method you added. [source](https://github.com/npm/map-workspaces/blob/main/lib/index.js#L29-L40)

2023-08-15 16:08 UTC, closed without merging