docs: document log order
vercel/turbo pull request #5463
Opened 2023-07-05 18:13 UTC by chris-olszewski

### Description

Adds documentation for `--log-order` #3916 including a callout of our special behavior on Github Actions.

### Testing Instructions

Eyes

2023-07-05 19:19 UTC, anthonyshew requested changes

2023-07-05 19:19 UTC, anthonyshew commented on docs/pages/repo/docs/reference/command-line-reference/run.mdx
> +turbo decide based on its own heuristics.
We're mentioning "using heuristics" but I'm left wondering what _are_ those heuristics? What behaviors should I be expecting to see?

2023-07-05 19:19 UTC, anthonyshew commented on docs/pages/repo/docs/reference/command-line-reference/run.mdx
> +| stream  | show output as soon as it is available    |
Start phrase with a capital letter.

2023-07-05 19:19 UTC, anthonyshew commented on docs/pages/repo/docs/reference/command-line-reference/run.mdx
> +| grouped | show output grouped by task               |
Capital letter as well!

2023-07-05 19:19 UTC, anthonyshew commented on docs/pages/repo/docs/reference/command-line-reference/run.mdx
> +  If log order is set to auto and turbo detects that it is running on Github Actions, then turbo will
turbo should be code formatted. `turbo`

2023-07-05 19:19 UTC, anthonyshew commented on docs/pages/repo/docs/reference/command-line-reference/run.mdx
> +  If this isn't desired, then the behavior can be opted out of by setting the log order to stream or grouped directly.
```suggestion
  You can opt out of this behavior by setting a log order of your own.
```

2023-07-06 13:28 UTC, arlyon approved these changes
No comments beyond Anthony's request so approving to unblock :)

2023-07-12 00:13 UTC, anthonyshew approved these changes

2023-07-12 00:13 UTC, anthonyshew commented
Oops, sorry for being a blocker! Awesome ship, @chris-olszewski!

2023-07-17 17:40 UTC, merged