Wire filewatching to daemon server
vercel/turbo pull request #5916
Opened 2023-09-08 21:51 UTC by gsoltis

### Description

 - daemon asynchronously loads filewatching
 - filewatching errors and/or repo root being removed trigger server shutdown
 - filewatcher constructor is now fully asynchronous
 - running gRPC server is now a function call, rather than a struct to simplify ownership and lifecycle of filewatching-related tasks.

### Testing Instructions

Existing tests, plus an additional test at the server level for root deletion.

2023-09-13 20:17 UTC, NicholasLYang requested changes
Just one question around using `oneshot` vs `mpsc` channels

2023-09-13 20:17 UTC, NicholasLYang commented on crates/turborepo-lib/src/daemon/server.rs
> +    let (gprc_shutdown_tx, shutdown_reason) = oneshot::channel();
should this be `grpc`?

2023-09-13 20:30 UTC, gsoltis commented on crates/turborepo-lib/src/daemon/server.rs
> +        (Arc::new(Mutex::new(Some(tx))), rx)
The original implementation had mutex + oneshot, which is why I kept it, but I think either setup could work. The failure scenarios are either you grab the mutex and the channel is `None`, or you try to send on the `mpsc` and get a `SendError`. We already explicitly ignore the error on send (the corresponding task may have already exit), so maybe that's a little simpler?

2023-09-13 21:50 UTC, gsoltis commented on crates/turborepo-lib/src/daemon/server.rs
> +        (Arc::new(Mutex::new(Some(tx))), rx)
Switched to `mpsc`. Seems a little cleaner.

2023-09-13 21:50 UTC, gsoltis commented on crates/turborepo-lib/src/daemon/server.rs
> +    let (gprc_shutdown_tx, shutdown_reason) = oneshot::channel();
Yup, renamed.

2023-09-14 17:59 UTC, NicholasLYang approved these changes
Looks good!

2023-09-14 18:02 UTC, merged