fix(Turborepo): copy yarn berry config files when running `turbo prune`
vercel/turbo pull request #6073
Opened 2023-10-01 08:53 UTC by artberri

### Description

Fixes #6063 

- Copy `.yarnrc.yml` file when present during turbo prune to out and out/full w/docker
- Copy `.yarn/releases`, `.yarn/patches`, `.yarn/plugins`, `.yarn/releases`, `.yarn/sdks` and `.yarn/versions` folders when present during turbo prune to out and out/full w/docker.
- Add a new example for Yarn v2+ (berry)

These files and folders are required in Yarn V2+ with the `node-modules` node linker config to reproduce idempotent installations and should be included in the output folder. For more info about those folders and files:
https://yarnpkg.com/configuration/yarnrc
https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

### Testing Instructions

```sh
cd cli
make turbo
cd ../examples/with-berry
yarn install
turbo prune web # or turbo prune web --docker
```

2023-10-02 22:30 UTC, chris-olszewski requested changes
Thanks for the PR! I think including the `.yarnrc.yml` is a good fix along with `.yarn/releases` since that can get referenced from `.yarnrc.yml`, but I'm not convinced on the rest of the changes are desired. 

We don't want prune to copy files that will be unused on the Docker image and `.yarn/plugins`, `.yarn/sdks`, and `.yarn/versions` all seem like for most projects they wouldn't be necessary in order to run a server. If you have an example where these are necessary, I think it would be acceptable to hide this behavior behind a flag. Maybe `--include-full-config` or something along those lines.

Is that okay with you?

2023-10-02 22:30 UTC, chris-olszewski commented on crates/turborepo-lib/src/commands/prune.rs
> +            RelativeUnixPath::new(".yarn/sdks").unwrap(),
Reading the description of what is in `.yarn/sdks` I'm not sure if most Docker images want these files.

2023-10-02 22:30 UTC, chris-olszewski commented on crates/turborepo-lib/src/commands/prune.rs
> +        ),
We already copy the patches on line 196.
```suggestion
```

2023-10-03 09:44 UTC, weyert commented
@artberri  Isn't the prune command already doing that?

2023-10-03 17:17 UTC, chris-olszewski approved these changes
Your explanation makes sense. Again, thank you for the PR and the properly set up berry example. I'll try to get this merged in for the next patch release.

2023-10-03 17:33 UTC, weyert commented
Would this file to be the right place to add `pnpm` files too? E.g. `pnpm-workspace.yaml` and `.pnpmfile.cjs`?

2023-10-03 17:47 UTC, chris-olszewski commented
> Would this file to be the right place to add `pnpm` files too? E.g. `pnpm-workspace.yaml` and `.pnpmfile.cjs`?

Yes to `.pnpmfile.cjs`, we actually already copy `pnpm-workspace.yaml` [here](https://github.com/vercel/turbo/blob/main/crates/turborepo-lib/src/commands/prune.rs#L94)

2023-10-03 18:34 UTC, merged