WIP: Improve performance by reworking calculate_file_hashes
vercel/turbo pull request #6148
Opened 2023-10-11 15:05 UTC by arlyon

### Description

A large amount of time prepping turbo for execution is spent in `calculate_file_hashes`. This function discovers all the workspaces in the project and computes hashes for all the files inside it. It processes a package in 3 major ways

- git without inputs: run git status and ls-tree to calculate file hashes
- git with file inputs: walk the glob inputs and select files from those
- manual: do a walk using the `ignore` crate, and perform globbing manually

This PR adds some instrumentation and helps improve perf in the first case, but there are a few other things that could be worked on before this is merged:

- the cost of calculating the 'git without inputs' case is now very very low after pre-building the cache; we could probably collect those tasks and execute them on one thread, and do all the 'git with inputs' on another
- the performance of the manual case has not been evaluated in depth (yet)
- we could maybe be performing walks and hashes in parallel, rather than walking then hashing. walking is not very CPU intensive. 

### Testing Instructions

We do not have E2E benches _yet_, this is a precursor to that (along with #6146)

2023-10-11 17:37 UTC, mehulkar reviewed
Is it possible to split up the instrumentation piece into another PR so we can potentially have before/after timings after the rework?

2023-10-12 12:47 UTC, arlyon commented
@mehulkar I dropped that commit and moved it into it's own PR

2023-11-22 19:45 UTC, chris-olszewski requested changes
Overall the changes seem solid to me. The breakages from the e2e and integration tests seem valid and should be addressed.

2023-11-22 19:45 UTC, chris-olszewski commented on crates/turborepo-scm/src/package_deps.rs
> +                let mut map: HashMap<&AnchoredSystemPath, (GitHashes, Vec<_>)> = Default::default();
```suggestion
                let mut map: HashMap<&AnchoredSystemPath, (GitHashes, Vec<_>)> = HashMap::with_capacity({
                    let (lower, upper) = package_roots.size_hint();
                    upper.unwrap_or(lower)
                });
```

2023-11-22 19:45 UTC, chris-olszewski commented on crates/turborepo-scm/src/package_deps.rs
> +                    let (hashes, files) = map.entry(package).or_default();
Just asking due to the use of `entry`, but do we ever expect a `package` to appear twice in `package_roots`? If so I believe `files` will contain two duplicate entries. Maybe just use an `map.insert` or dedupe `package_roots` before we iterate through them.

2024-01-10 11:23 UTC, arlyon commented
This PR is being put on ice until we figure out a plan for `optimize`

2024-01-10 11:23 UTC, closed without merging