fix: Hard error on spaces
vercel/turbo pull request #6596
Opened 2023-11-27 19:35 UTC by NicholasLYang

### Description

When we fail to start the `SpacesClient`, this can lead to an error when we try to close it at the end of a run. Instead of erroring, we simply log out the error and continue, since spaces is not critical to execution.

### Testing Instructions

Added a test for spaces failure that ensures we exit with 0

Closes TURBO-1764

2023-11-27 20:51 UTC, chris-olszewski requested changes
Primarily concerned with avoiding hitting prod in our test runs.

I also think we can avoid using a separate task to manage the spinner.

2023-11-27 20:51 UTC, chris-olszewski commented on turborepo-tests/integration/tests/spaces-failure.t
> +  $ ${TURBO} run build --token foobarbaz --team bat --output-logs none > /dev/null 2>&1
Can we use the `--api` flag to avoid hitting prod in our tests runs?

2023-11-27 20:51 UTC, chris-olszewski commented on crates/turborepo-lib/src/run/summary/mod.rs
> +        };
```suggestion
       let (result, spinner) = tokio::join!(spaces_client_handle.finish_run(exit_code, ended_at), spinner_fut);
       if let Err(err) = result {
           warn!("Error sending to space: {}", err);
       };
```

2023-11-27 21:20 UTC, NicholasLYang commented on crates/turborepo-lib/src/run/summary/mod.rs
> +        });
Will this get triggered? I was under the impression that this wouldn't get run unless we actively await or spawn it

2023-11-27 21:24 UTC, NicholasLYang commented on crates/turborepo-lib/src/run/summary/mod.rs
> +       let (result, spinner) = tokio::join!(spaces_client_handle.finish_run(exit_code, ended_at), spinner_fut);
Actually, wouldn't this wait on both the spinner and `finish_run`? So we'd be waiting a whole second unnecessarily. @chris-olszewski

2023-11-27 21:40 UTC, chris-olszewski approved these changes

2023-11-28 15:06 UTC, merged

2023-11-30 04:13 UTC, mehulkar commented on turborepo-tests/integration/tests/_fixtures/spaces_failure/turbo.json
> +    "id": "my-space"
@NicholasLYang If you're going to create a separate fixture, make sure to delete things that aren't relevant to it (like most of this turbo.json. Also, there's a section in the README for if what you really want is a custom turbo.json https://github.com/vercel/turbo/tree/main/turborepo-tests/integration#custom-turbojson