Only warn for ESLint issues in editor.
vercel/turbo pull request #6821
Opened 2023-12-18 05:53 UTC by anthonyshew

### Description

### Testing Instructions

2023-12-18 14:15 UTC, tknickman requested changes
Not a fan of this personally. Red is error, yellow is warn. 

I prefer the feedback of what will be an error in all environments, in my editor, immediately. 

Also, eslint issues _do_ block CI for our packages.

2023-12-18 16:04 UTC, anthonyshew commented
Noice. Docs issues will be blocking now too.

I guess the idea is: All squigglies are blocking. Red is TypeScript. Yellow is ESLint.

I didn't write that very well in my original description.

2023-12-18 16:04 UTC, anthonyshew commented
And, yes, I can see this being preferential. I was curious to see if others would like/not like this. 😄

2023-12-18 17:15 UTC, tknickman commented
👍🏼 I see what you're saying, but I think this is more of a preferential thing that we may not want to commit - I think using the underline color to indicate the _source_ instead of _severity_ is pretty non-standard and may be a little confusing for those used to the other way.  

I may be wrong here though, we can poll the team. But I think the yellow / warn and red / error visual queue is pretty hardcoded into our brains.

2023-12-18 18:07 UTC, mehulkar reviewed
I'm with Tom and I would be confused by this change. We should rationalize our TS and ESlint setup so that there isn't duplication in the things they check, but I'd still like red to mean error and yellow to mean warn.

2023-12-19 02:50 UTC, anthonyshew commented
Fine by me! I'll close this.

2023-12-19 02:50 UTC, closed without merging