Some branding and README stuff.
vercel/turbo pull request #7129
Opened 2024-01-27 18:21 UTC by anthonyshew

### Description

### Testing Instructions

2024-01-28 23:28 UTC, tknickman requested changes

2024-01-28 23:28 UTC, tknickman commented on packages/turbo-vsc/package.json
> +  "displayName": "Turbo LSP",
```suggestion
  "displayName": "Turborepo LSP",
```

We only use Turborepo, or `turbo`. `turbo` refers to the executable directly, and Turborepo to the product.

2024-01-28 23:28 UTC, tknickman commented on packages/turbo-vsc/package.json
> +      "title": "Turbo LSP",
Same as above

2024-01-29 20:59 UTC, mehulkar approved these changes

2024-01-30 00:01 UTC, anthonyshew commented on packages/turbo-vsc/package.json
> +      "title": "Turbo LSP",
```suggestion
      "title": "Turborepo LSP",
```

2024-01-30 17:59 UTC, tknickman approved these changes

2024-01-30 19:35 UTC, merged