chore: update github actions
vercel/turbo pull request #7224
Opened 2024-02-01 23:14 UTC by ForsakenHarmony

### Description

The `node16` runner is deprecated, I updated all the actions I could here.

Still missing:
https://github.com/pnpm/action-setup (removed in favor of corepack, but that needs to be tested)

2024-02-08 19:08 UTC, mehulkar reviewed
Kicking off some dry runs for CI workflows to validate:

- ❌ [Dry run for turborepo release](https://github.com/vercel/turbo/actions/runs/7834625823)
- [Benchmark](https://github.com/vercel/turbo/actions/runs/7834636474)
- ❌ [Library release](https://github.com/vercel/turbo/actions/runs/7834642627)

2024-02-08 19:23 UTC, mehulkar requested changes
Looks like there's some glibc missing issue for both our release workflows. We'd need to work those out before merge

2024-02-09 16:04 UTC, mehulkar approved these changes

2024-02-15 13:24 UTC, arlyon commented on .github/workflows/lsp.yml
Answered in DM but repeating here; the LSP release is expected to fail in one case so I will resolve this.

2024-02-19 02:58 UTC, kdy1 approved these changes

2024-02-19 02:58 UTC, kdy1 commented on .github/actions/setup-rust/action.yml
>          repo-token: ${{ inputs.github-token }}
I think we may add some comments describing that this is to avoid rate limit.

2024-02-19 02:58 UTC, kdy1 commented on .github/actions/setup-rust/action.yml
>          repo-token: ${{ inputs.github-token }}
Mainly because passing token to `setup-rust` action looks weird.

2024-06-15 22:22 UTC, anthonyshew commented
Will close this as stale.

2024-06-15 22:22 UTC, closed without merging