Ignore .d.ts files in tsconfig paths handling
vercel/turbo pull request #7228
Opened 2024-02-02 14:07 UTC by timneutkens

### Description

Currently Turbopack tries to handle the `.d.ts` file when resolving tsconfig.json `paths`. The `.d.ts` file should be ignored in that case.

### Testing Instructions

2024-02-02 14:07 UTC, timneutkens commented
* `main`
  * **#7228** <a href="https://app.graphite.dev/github/pr/vercel/turbo/7228?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @timneutkens and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-02-02 14:13 UTC, ForsakenHarmony approved these changes

2024-02-02 14:29 UTC, sokra requested changes

2024-02-02 14:29 UTC, sokra commented on crates/turbopack-ecmascript/src/typescript/resolve.rs
> -                                    // tsconfig paths are always relative requests
Maybe preserve this comment

2024-02-02 14:29 UTC, sokra commented on crates/turbopack-ecmascript/src/typescript/resolve.rs
> +                                    s if s.ends_with("d.ts") => None,
I think that's.not correct in turbotracing when resolving typings

2024-05-08 08:54 UTC, timneutkens commented
This was handled differently.

2024-05-08 08:54 UTC, closed without merging