feature: Add invalidate flag to logout
vercel/turbo pull request #7444
Opened 2024-02-21 00:31 UTC by Zertsov

### Description
Allows for `turbo logout --invalidate` which should call to the API to actually remove the token from the account.

2024-02-21 00:31 UTC, Zertsov commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/vercel/turbo/7444?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#7444** <a href="https://app.graphite.dev/github/pr/vercel/turbo/7444?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#7443** <a href="https://app.graphite.dev/github/pr/vercel/turbo/7443?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#7407** <a href="https://app.graphite.dev/github/pr/vercel/turbo/7407?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Zertsov and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-02-21 18:39 UTC, chris-olszewski requested changes
I think some more testing is needed.

2024-02-21 18:39 UTC, chris-olszewski commented on crates/turborepo-auth/src/auth/logout.rs
> +    })?;
```suggestion
    let content = path.read_to_string()?;
```

2024-02-21 18:39 UTC, chris-olszewski commented on crates/turborepo-auth/src/lib.rs
> +        let token = std::fs::read_to_string(path)?;
I don't think this is correct, don't we want to be parsing the contents of the file and extracting the token or have we switched to just saving them raw?

Good candidate for a unit test
```suggestion
    pub fn from_file(path: &AbsoluteSystemPath) -> Result<Self, Error> {
        let token = path.read_to_string()?;
```

2024-03-01 22:17 UTC, chris-olszewski requested changes
We need to increase our automated test coverage for the codebase.

A few notes:
 - A successful `turbo_dev logout --invalidate` doesn't have any output, hard to tell if it succeeded or not
 - Trying to login with an invalidated token has a very unhelpful error message:
 ```
[1 olszewski@chriss-mbp] /Users/olszewski/code/vercel/turborepo $ turbo_dev login --sso-team=vercel
  × Error making HTTP request: error decoding response body: missing field `token` at line 1 column 77
  ├─▶ error decoding response body: missing field `token` at line 1 column 77
  ╰─▶ missing field `token` at line 1 column 77
 ```

2024-03-01 23:25 UTC, Zertsov commented
> We need to increase our automated test coverage for the codebase.
> 
> A few notes:
>  - A successful `turbo_dev logout --invalidate` doesn't have any output, hard to tell if it succeeded or not
>  - Trying to login with an invalidated token has a very unhelpful error message:
>  ```
> [1 olszewski@chriss-mbp] /Users/olszewski/code/vercel/turborepo $ turbo_dev login --sso-team=vercel
>   × Error making HTTP request: error decoding response body: missing field `token` at line 1 column 77
>   ├─▶ error decoding response body: missing field `token` at line 1 column 77
>   ╰─▶ missing field `token` at line 1 column 77
>  ```
> 
> 

Agreed that the output should be there, I can fix that quick. The login seems to be a separate issue though.

2024-03-06 18:02 UTC, chris-olszewski approved these changes
One minor change, but I think this is fine. Should we document this?

2024-03-06 20:55 UTC, Zertsov commented on crates/turborepo-api-client/src/lib.rs
> +            #[serde(rename = "invalidToken")]
I think (from the API docs) that it _always_ has this field in the response, but I can add this regardless

2024-03-07 16:00 UTC, merged

2024-03-07 16:00 UTC, Zertsov commented
### Merge activity

* **Mar 7, 11:00 AM EST**: @Zertsov merged this pull request with [Graphite](https://app.graphite.dev/github/pr/vercel/turbo/7444).