feat(examples): add example-with-typeorm
vercel/turbo pull request #8143
Opened 2024-05-15 09:29 UTC by cgoinglove

This pull request introduces a new typeorm-service package to the official TurboRepo examples. The aim is to demonstrate the implementation of a robust service layer using TypeORM with a custom dependency injection (DI) mechanism. This example is designed to help developers integrate a more structured backend architecture with their existing Next.js applications, leveraging TypeORM for ORM capabilities.

<img width="1164" alt="turborepo-orm" src="https://github.com/vercel/turbo/assets/86150470/2662321f-c5ab-4b26-9623-b48bc611dbaa">

2024-06-16 00:49 UTC, anthonyshew requested changes
Thanks for the contribution!

A few things I'm noticing right away:
- Out of the box, the none of the `build`, `test`, or `lint` commands work. Can those be fixed?
- We've released Turborepo 2 since this was made. Could you upgrade it with `npx @turbo/codemod upgrade`?

After those are taken care of, I'll take a deeper look.

2024-06-18 04:57 UTC, cgoinglove commented
Hi,

Thank you for your feedback. I have addressed the issues you mentioned:

Fixed the build, test, and lint commands so they now work out of the box.
Upgraded Turborepo to version 2 using npx @turbo/codemod upgrade.
Please let me know if there are any other changes or improvements needed.

Thank you! @anthonyshew

2024-07-13 13:05 UTC, anthonyshew commented
I'm still seeing a lot of errors when I run `turbo test`.

2024-07-14 15:32 UTC, cgoinglove commented
I'm still seeing a lot of errors when I run `turbo test`.

This issue occurs because the example user might not have verified the database connection configuration before running the test code.

To address this, I added a comment in the test code:

```typescript
/**
 *
 * If you have correctly configured the database connection information in 'packages/typeorm-service/src/orm-config.ts',
 * remove this skipIf statement and run the tests.
 */

const todoService = inject(TodoService);

suite.skipIf(true)("Todo", () => {
  let id: Todo["id"];

  test("Insert", async () => {
    const newTodo = await todoService.add("Hello World");

    id = newTodo.id;

    expect(newTodo.complete).toBeFalsy();
  });
});
```

Additionally, for example users, I have updated the README to include instructions on entering database connection information and provided a MySQL Dockerfile and execution script.

Thank you for your(@anthonyshew ) comment. I have been waiting for your feedback and appreciate you reaching out.

2024-07-23 12:58 UTC, anthonyshew commented
I'd prefer to have these be unit tests, mocking the database call. Is that something you could do?

2024-07-23 14:03 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 89fac8b92c58da19578510abb9f9cc8f57c72872

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-07-27 14:15 UTC, merged