Tree Shaking grouping of items
vercel/turbo pull request #8420
Opened 2024-06-11 10:07 UTC by sokra

### Description

add test case

### Testing Instructions

2024-06-11 10:07 UTC, sokra commented on crates/turbopack-ecmascript/tests/tree-shaker/analyzer/grouping/input.js
> +export const y = x;
Removing this line fixes the problem

2024-06-11 10:12 UTC, sokra commented on crates/turbopack-ecmascript/tests/tree-shaker/analyzer/grouping/output.md
> +};
It should better import `x` instead of exporting it

2024-06-11 10:14 UTC, sokra commented on crates/turbopack-ecmascript/tests/tree-shaker/analyzer/grouping/output.md
> +};
```suggestion
```

These are not necessary. It only need to import the last Write to a variable. And the declaration of it

2024-06-11 10:14 UTC, sokra commented on crates/turbopack-ecmascript/tests/tree-shaker/analyzer/grouping/output.md
> +};
I feel like it's wrong that a module exports a variable that it didn't declare.

2024-06-14 12:21 UTC, sokra commented on crates/turbopack-ecmascript/tests/tree-shaker/analyzer/ipc-evaluate/output.md
>  };
double export

2024-06-14 12:50 UTC, kdy1 requested changes
Currently an execution test fails because import statements in `module evaluation` node is removed without injecting `__turbopack_import__`

2024-06-17 03:58 UTC, kdy1 approved these changes

2024-06-17 08:08 UTC, merged