fix: Fix `the let bug`
vercel/turbo pull request #8656
Opened 2024-07-03 03:58 UTC by kdy1

### Description

I faced this bug while working on https://github.com/vercel/turbo/pull/8523. Tree shaking inevitably creates direct imports for let bindings, and when the LHS of `+=` is imported/exported, it triggers a bug.

### Testing Instructions

Test references changed quite a lot.

2024-07-03 07:57 UTC, sokra requested changes

2024-07-03 07:57 UTC, sokra commented on crates/turbopack-ecmascript/tests/analyzer/graph/assign/graph-explained.snapshot
> +  ⚠️  pattern without value
That doesn't look correct

2024-07-03 09:59 UTC, sokra approved these changes
a test case would be great

2024-07-04 01:34 UTC, bgw approved these changes

2024-07-04 01:50 UTC, merged